name: '[Build]'
run-name: "Build for '${{ github.ref_name }}'"

on:
    push:
        branches:
            - 'hotfix**'
            - 'master'

jobs:
  string-tester:
    runs-on: ubuntu-latest
    env:
      STABLE_BRANCH: ${{github.ref_name}}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove hotfix substring 
        id: clean-branchname
        if: contains(env.STABLE_BRANCH, 'hotfix')
        shell: bash
        run: |
            prefix="hotfix-"
            input="$STABLE_BRANCH"
            output=${input#"$prefix"}
            echo "STABLE_BRANCH=$output" >> $GITHUB_ENV

      - name: Print 
        id: print
        shell: bash
        run: |
            echo "The ref name is $STABLE_BRANCH"        
                